modLoader = "javafml"
loaderVersion = "[47,)"
#updateJSONURL=""
issueTrackerURL = "https://github.com/ramidzkh/Applied-Botanics/issues"
displayURL = "https://github.com/ramidzkh/Applied-Botanics#readme"
logoFile = "logo.png"
#credits="Thanks for this example mod goes to Java"
authors = "ramidzkh"
license = "See GitHub repository for details"

[[mods]]
modId = "appbot"
version = "${version}"
displayName = "Applied Botanics"
description = "mana through ae2, what could go wrong"
updateJSONURL = "https://api.modrinth.com/updates/applied-botanics/forge_updates.json"

[[dependencies.appbot]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.appbot]]
modId = "ae2"
mandatory = true
versionRange = "[15.0.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.appbot]]
modId = "botania"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
